version: '3'

tasks:
  build:linux:
    cmds:
      - cross build --target x86_64-unknown-linux-musl --release

  build:windows:
    cmds:
      - cross build --target x86_64-pc-windows-gnu --release

  build:macos:
    cmds:
      - cross build --target x86_64-apple-darwin --release

  build:
    cmds:
      - cargo build --release
  
  run:
    cmds:
      - cargo run