name: Build and Release

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Rust
        uses: actions/setup-rust@v1

      - name: Build for Linux
        run: cargo build --release --target x86_64-unknown-linux-gnu

      - name: Archive Linux build
        uses: actions/upload-artifact@v2
        with:
          name: Linux
          path: target/x86_64-unknown-linux-gnu/release/

      - name: Build for Windows
        run: cargo build --release --target x86_64-pc-windows-msvc

      - name: Archive Windows build
        uses: actions/upload-artifact@v2
        with:
          name: Windows
          path: target/x86_64-pc-windows-msvc/release/

      - name: Build for macOS
        run: cargo build --release --target x86_64-apple-darwin

      - name: Archive macOS build
        uses: actions/upload-artifact@v2
        with:
          name: macOS
          path: target/x86_64-apple-darwin/release/

  release:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Download Linux build
        uses: actions/download-artifact@v2
        with:
          name: Linux

      - name: Create Linux release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            target/x86_64-unknown-linux-gnu/release/*
          tag_name: v1.0.0
          release_name: Release v1.0.0 (Linux)

      - name: Download Windows build
        uses: actions/download-artifact@v2
        with:
          name: Windows

      - name: Create Windows release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            target/x86_64-pc-windows-msvc/release/*
          tag_name: v1.0.0
          release_name: Release v1.0.0 (Windows)

      - name: Download macOS build
        uses: actions/download-artifact@v2
        with:
          name: macOS

      - name: Create macOS release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            target/x86_64-apple-darwin/release/*
          tag_name: v1.0.0
          release_name: Release v1.0.0 (macOS)
